import Head from 'next/head'
import Header from '../components/header'
import Timelines from '../components/Timelines'
import logo from '../public/logo.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>亚太辩论</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header image={logo} title="第十一届亚太辩论比赛" />
          <Timelines />
      </main>
    </div>
  )
}
