import Form from '../components/form'
import Head from 'next/head'

function Registration() {
  return (
    <>
      <Head>
        <title>选手报名系统</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form information={['Name', 'Email Address', 'School', 'Country', 'Topic']} />
      </>
      );
}

export default Registration;