import Topic from "../components/topic";
import Head from 'next/head'
// import topic from "../public/topics.json"

function TopicPage({ topics }) {
    const { data } = topics
    // const { data } = topic
    console.log(data)
    return (
        <>
        <Head>
        <title>比赛辩题</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <Topic topics={data}></Topic>
            </>
    );
}

export default TopicPage;

export async function getServerSideProps() {
    const response = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}matches`, {
        method: 'GET',
        headers: {
            'Content-type': 'application/json'
        }
    })
    const res = await response.json()
    return {
        props: {
            topics: res
        }
    }
}